server:
    port: 8001


### spring ############################################################
spring:
    datasource:
        driver-class-name: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@lsunja.asuscomm.com:1521/xe
        username: TEST
        password: tower0814

    banner:
        location: banner_account.txt    